### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку Virt Mem Max Шугаепов Ильнур

### ISSUE THREAD

**Issue by ilnurshug** [ilnurshug/au-linux-kernel-spring-2016#3]
https://github.com/ilnurshug/au-linux-kernel-spring-2016/commit/a96986d9d459937671476cb2bcbcff7df3d2e3d9

**Comment by eabatalov** [comment]
The general idea is right. Except malloc that is used for unknown purpose.
80 points out of 100.
